"""Upgrade to SQLAlchemy 2.0

Revision ID: 3abfabf3e216
Revises: edf45abba84b
Create Date: 2025-12-25 13:58:09.083430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3abfabf3e216'
down_revision: Union[str, Sequence[str], None] = 'edf45abba84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link_click_log', 'link_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('link_click_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('link_metadata', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('link_metadata', 'long_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('link_metadata', 'clicks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('link_metadata', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('link_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('links', 'long_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('links', 'long_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('link_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('link_metadata', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('link_metadata', 'clicks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('link_metadata', 'long_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('link_metadata', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('link_click_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('link_click_log', 'link_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
