"""Add created_at and updated_at to relevant models

Revision ID: edf45abba84b
Revises: eeaec1e12d28
Create Date: 2025-12-25 13:37:38.946670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf45abba84b'
down_revision: Union[str, Sequence[str], None] = 'eeaec1e12d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_click_log', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('link_metadata', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('link_metadata', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('links', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('links', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'updated_at')
    op.drop_column('links', 'created_at')
    op.drop_column('link_metadata', 'updated_at')
    op.drop_column('link_metadata', 'created_at')
    op.drop_column('link_click_log', 'created_at')
    # ### end Alembic commands ###
