"""Initialize DB

Revision ID: eeaec1e12d28
Revises: 
Create Date: 2025-12-25 13:17:22.573470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeaec1e12d28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_long_url'), 'links', ['long_url'], unique=False)
    op.create_table('link_click_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.String(), nullable=True),
    sa.Column('click_ip', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_click_log_id'), 'link_click_log', ['id'], unique=False)
    op.create_index(op.f('ix_link_click_log_link_id'), 'link_click_log', ['link_id'], unique=False)
    op.create_table('link_metadata',
    sa.Column('link_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('long_url', sa.String(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('last_ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_link_metadata_link_id'), 'link_metadata', ['link_id'], unique=False)
    op.create_index(op.f('ix_link_metadata_name'), 'link_metadata', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_metadata_name'), table_name='link_metadata')
    op.drop_index(op.f('ix_link_metadata_link_id'), table_name='link_metadata')
    op.drop_table('link_metadata')
    op.drop_index(op.f('ix_link_click_log_link_id'), table_name='link_click_log')
    op.drop_index(op.f('ix_link_click_log_id'), table_name='link_click_log')
    op.drop_table('link_click_log')
    op.drop_index(op.f('ix_links_long_url'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
